name: Pull request checks

on:
  pull_request:
  push:
    branches:
      - "main"

jobs:
  tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - uses: actions/setup-python@v4
        with:
          python-version: "3.x"

      - name: Install dependencies
        run: python3 -m pip install -r requirements.txt
      
      - name: Build and install program
        run: pip install .

      - name: Run tests
        run: pytest --verbose
